In [0]:
import numpy as np
import tensorflow as tf

In [0]:
from tensorflow.keras.utils import get_file

creating tenosr with random mehod of tensorflow , maxval is neccesssary when we are going to specifiy the datatype of values in the tensor

In [0]:
tensor1=tf.random.uniform([5,5],maxval=30,seed=10,dtype=tf.int32)

In [0]:
tensor2=tf.random.uniform([5,5],maxval=100,seed=10,dtype=tf.int32)

we can create dataset using tf.data.Dataset.from_tensor_slice menthod

In [0]:
dataset1=tf.data.Dataset.from_tensor_slices(tensor1)
print([i.numpy() for i in dataset1.take(2)])

[array([ 0,  2,  5, 17, 12], dtype=int32), array([12, 23,  5, 19, 20], dtype=int32)]


In [0]:
dataset2=tf.data.Dataset.from_tensor_slices(tensor2)
dataset2

<TensorSliceDataset shapes: (5,), types: tf.int32>

we can inspect the tensor using elemnet_spect property 


In [0]:
dataset1.element_spec

TensorSpec(shape=(5,), dtype=tf.int32, name=None)

zip method combine two dataset in stack form like vstack or hstack genarlly vstcak is used

In [0]:
combine_dataset=tf.data.Dataset.zip((dataset1,dataset2))

In [0]:
combine_dataset.element_spec

(TensorSpec(shape=(5,), dtype=tf.int32, name=None),
 TensorSpec(shape=(5,), dtype=tf.int32, name=None))

we can print contennt of combined dataset tensor using this for loop of iter method



In [0]:
for i in combine_dataset.take(2):
  print(i)

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0,  2,  5, 17, 12], dtype=int32)>, <tf.Tensor: shape=(5,), dtype=int32, numpy=array([34, 13,  0, 38, 99], dtype=int32)>)
(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([12, 23,  5, 19, 20], dtype=int32)>, <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 4, 92, 89, 80, 64], dtype=int32)>)


#**Loading numpy array in the memory and training one simple model.**

In [0]:
train,test=tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
train_data,labels=train
train_data=train_data/255.0

In [0]:
training_dataset=tf.data.Dataset.from_tensor_slices((train_data,labels))

In [0]:
training_dataset.element_spec

(TensorSpec(shape=(28, 28), dtype=tf.float64, name=None),
 TensorSpec(shape=(), dtype=tf.uint8, name=None))

# Guide to use generator to build input pipelines 

## yeild keyword is just like return keyword in functions but it dosen't end function execution flow after returning the value.

In [0]:
def count(stop):
  i = 0
  while i<stop:
    yield i
    i += 1

In [0]:
for n in count(10):
  print(n)

0
1
2
3
4
5
6
7
8
9


In [0]:
ds_Counter=tf.data.Dataset.from_generator(count,args=[100],output_shapes=(),output_types=tf.int32)
ds_Counter.element_spec

TensorSpec(shape=(), dtype=tf.int32, name=None)

In [0]:
for count_batch in ds_Counter.repeat().batch(10).take(20):
  print(count_batch.numpy())

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69]
[70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89]
[90 91 92 93 94 95 96 97 98 99]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69]
[70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89]
[90 91 92 93 94 95 96 97 98 99]


In [0]:
size=np.random.randint(0,10)

In [0]:
np.random.normal(size=(size,))

array([-0.72179242, -0.47758388])

## yeild keyword is just like return keyword in functions but it dosen't end function execution flow after returning the value.


*   this method is for sequence datsaset in which the input sequences does not have fix length the we should use this method
*   for this classes how we can able to build pipeline through from_generator function its examples is shown below.
* for this kind of sequence data genearally padded_batch method should be use beacuse they dont have fix size that's why padding in shuch cases necessary.




In [0]:
def gen_series():
  i=0
  while True:
    size=np.random.randint(0,10)
    yield i,np.random.normal(size=(size,))
    i+=1

In [0]:
for i,series in gen_series():
  print(i,":",str(series))
  if i>=5:
    break

0 : [-1.83278414  2.70088551 -1.29823003  0.80067206 -0.54414125 -0.47762034
 -0.65732498  1.54710453 -1.28211411]
1 : [-0.95274469  0.93444678 -0.92942707 -1.91951745  0.17045007 -0.55261076
  0.02864744]
2 : [ 0.04159239 -0.84904169  1.06019583  0.30041129  1.26000343 -0.19721676
  2.37940582  0.35967574  0.88384824]
3 : [-1.43723181 -0.03533434 -2.13672327  1.01269084 -0.72983846  0.9176672
  1.19202712 -0.36509494  0.96899044]
4 : [-0.99430593]
5 : [ 0.76257566 -0.26496044 -1.89362836  0.82397426 -0.28752382  0.33587271]


In [0]:
ds_series=tf.data.Dataset.from_generator(gen_series,
                                        output_types=(tf.int32,tf.float32),
                                         output_shapes=((),(None,))
                                         )
ds_series

<FlatMapDataset shapes: ((), (None,)), types: (tf.int32, tf.float32)>

In [0]:
ds_series_batch=ds_series.shuffle(20).padded_batch(10,padded_shapes=([],[None,]))

ids,sequences=next(iter(ds_series_batch))
print(ids)
print()
print(sequences.numpy())

tf.Tensor([ 0  1 15 13  7 10 24  5 27 17], shape=(10,), dtype=int32)

[[-1.1867411  -0.05611203  0.          0.          0.          0.
   0.          0.        ]
 [-0.48558477  0.06515926  0.          0.          0.          0.
   0.          0.        ]
 [-0.9246901  -0.3997179   0.          0.          0.          0.
   0.          0.        ]
 [ 1.5991867  -0.43852106  0.          0.          0.          0.
   0.          0.        ]
 [-1.0329858  -0.617649    1.4838111   0.7094071   0.16340688  0.4523243
   0.69156945  2.0802364 ]
 [-1.1679424  -0.9928939   0.43885055  0.          0.          0.
   0.          0.        ]
 [-0.05163113  0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.09277311 -0.17964333 -0.21321875 -0.10473029  0.          0.
   0.          0.        ]
 [ 0.12834236  0.03361898  0.3188944   0.04209754 -1.6741658  -1.3082092
  -0.93649584  1.0305464 ]
 [-0.04707785 -1.2049049   0.          0.          0.          0.
   0.        